"""app configuration: preferences, provider profiles, secret refs, usage

Revision ID: 49b6bbec3667
Revises: faf1ebf5cb97
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "49b6bbec3667"
down_revision: str | None = "faf1ebf5cb97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_profile",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("capability", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "capability"),
    )
    op.create_table(
        "secret_ref",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("ref", sa.String(length=256), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "name"),
    )
    op.create_table(
        "usage_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("capability", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usage_record_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_usage_record_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_usage_record_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_preferences")
    with op.batch_alter_table("usage_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_record_user_id"))
        batch_op.drop_index(batch_op.f("ix_usage_record_project_id"))
        batch_op.drop_index(batch_op.f("ix_usage_record_job_id"))

    op.drop_table("usage_record")
    op.drop_table("secret_ref")
    op.drop_table("provider_profile")
    # ### end Alembic commands ###
