"""job DAG: job, task, dependency, lease, task log, worker

Revision ID: faf1ebf5cb97
Revises: 62d9d3261b94
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "faf1ebf5cb97"
down_revision: str | None = "62d9d3261b94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker",
        sa.Column("worker_id", sa.String(length=64), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("heartbeat_ms", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("cost_limit_usd", sa.Float(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("first_done_ms", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_status"), ["status"], unique=False)

    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("resource_class", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("input_keys", sa.JSON(), nullable=False),
        sa.Column("output_key", sa.String(length=160), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            "ix_task_lease", ["status", "resource_class", "priority"], unique=False
        )

    op.create_table(
        "lease",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=64), nullable=False),
        sa.Column("expires_ms", sa.BigInteger(), nullable=False),
        sa.Column("heartbeat_ms", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    with op.batch_alter_table("lease", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lease_expires_ms"), ["expires_ms"], unique=False)

    op.create_table(
        "task_dependency",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_id"],
            ["task.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "depends_on_id"),
    )
    with op.batch_alter_table("task_dependency", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_dependency_depends_on_id"), ["depends_on_id"], unique=False
        )

    op.create_table(
        "task_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=24), nullable=False),
        sa.Column("worker_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_event_task_id"), ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_event_task_id"))

    op.drop_table("task_event")
    with op.batch_alter_table("task_dependency", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_dependency_depends_on_id"))

    op.drop_table("task_dependency")
    with op.batch_alter_table("lease", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lease_expires_ms"))

    op.drop_table("lease")
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index("ix_task_lease")
        batch_op.drop_index(batch_op.f("ix_task_job_id"))

    op.drop_table("task")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_status"))
        batch_op.drop_index(batch_op.f("ix_job_project_id"))

    op.drop_table("job")
    op.drop_table("worker")
    # ### end Alembic commands ###
