// Generated inputs of the frontend build (docs/ui/DESIGN_TOKENS.md, ADR 0032):
// - src/styles/tokens.css from docs/ui/tokens.json (committed; never hand-edited)
// - the bundled Geist and Geist Mono fonts (SIL OFL 1.1), from @fontsource-variable
// Run by predev/prebuild/pretest; `--check` fails when tokens.css is out of date.
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const tokensJson = resolve(root, "../docs/ui/tokens.json");
const tokensCss = resolve(root, "src/styles/tokens.css");

// shadcn/ui variable names mapped onto MosAic tokens (DESIGN_TOKENS.md §2). MosAic's own
// `accent` (amber) keeps its name; shadcn's hover "accent" is not used.
const SHADCN = [
  ["background", "bg"],
  ["foreground", "text"],
  ["card", "surface-1"],
  ["card-foreground", "text"],
  ["popover", "surface-2"],
  ["popover-foreground", "text"],
  ["primary", "accent"],
  ["primary-foreground", "accent-fg"],
  ["muted", "surface-2"],
  ["muted-foreground", "text-muted"],
  ["input", "border"],
  ["ring", "accent"],
  ["destructive", "reject"],
];

export function renderTokens(tokens) {
  const vars = (theme, indent = "  ") =>
    tokens.color.tokens.map((t) => `${indent}--${t.name}: ${t.value[theme]};`).join("\n");
  const space = tokens.spacing.tokens.map((t) => `  --${t.name}: ${t.value};`).join("\n");
  const radius = tokens.radius.tokens.map((t) => `  --${t.name}: ${t.value};`).join("\n");
  const type = tokens.type.groups
    .flatMap((g) => g.styles)
    .map(
      (s) =>
        `  --text-${s.name}: ${s.fontSize};\n  --text-${s.name}--line-height: ${s.lineHeight};\n` +
        `  --text-${s.name}--font-weight: ${s.fontWeight};`,
    )
    .join("\n");
  return `/* Generated by scripts/prepare.mjs from docs/ui/tokens.json. Do not edit. */

:root,
[data-theme="dark"] {
${vars("dark")}
  color-scheme: dark;
}

[data-theme="light"] {
${vars("light")}
  color-scheme: light;
}

@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
${vars("light", "    ")}
    color-scheme: light;
  }
}

:root {
${space}
}

@theme {
  /* Only token classes exist (invariant 15): Tailwind's default palette, sizes, radii
     and fonts are removed. */
  --color-*: initial;
  --text-*: initial;
  --radius-*: initial;
  --font-*: initial;
${radius}
${type}
  --font-sans: ${tokens.type.families.sans};
  --font-mono: ${tokens.type.families.mono};
}

@theme inline {
${tokens.color.tokens.map((t) => `  --color-${t.name}: var(--${t.name});`).join("\n")}
${SHADCN.map(([k, v]) => `  --color-${k}: var(--${v});`).join("\n")}
}
`;
}

// The bundled fonts (SIL OFL 1.1) from @fontsource-variable, renamed to the token family
// names ("Geist", "Geist Mono"), every unicode subset kept. Output is generated and ignored
// by git: src/assets/fonts/*.woff2 and src/styles/fonts.css.
const FONT_PACKAGES = [
  ["@fontsource-variable/geist", "Geist Variable", "Geist"],
  ["@fontsource-variable/geist-mono", "Geist Mono Variable", "Geist Mono"],
];

function writeFonts() {
  const out = resolve(root, "src/assets/fonts");
  mkdirSync(out, { recursive: true });
  let css = "/* Generated by scripts/prepare.mjs from @fontsource-variable. Do not edit. */\n";
  for (const [pkg, from, to] of FONT_PACKAGES) {
    const dir = resolve(root, "node_modules", pkg);
    let text = readFileSync(resolve(dir, "index.css"), "utf8");
    for (const m of text.matchAll(/url\(\.\/files\/([^)]+)\)/g)) {
      copyFileSync(resolve(dir, "files", m[1]), resolve(out, m[1]));
    }
    text = text.replaceAll(`'${from}'`, `"${to}"`).replaceAll("url(./files/", "url(../assets/fonts/");
    css += text + "\n";
  }
  writeFileSync(resolve(root, "src/styles/fonts.css"), css);
}

function main() {
  const tokens = JSON.parse(readFileSync(tokensJson, "utf8"));
  const css = renderTokens(tokens);
  if (process.argv.includes("--check")) {
    const current = existsSync(tokensCss) ? readFileSync(tokensCss, "utf8") : "";
    if (current !== css) {
      console.error("src/styles/tokens.css is out of date: run `npm run prepare-ui`");
      process.exit(1);
    }
  } else {
    mkdirSync(dirname(tokensCss), { recursive: true });
    writeFileSync(tokensCss, css);
  }
  writeFonts();
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
