"""L0 inventory: media files, streams, assets, chapter map, sidecars

Revision ID: 0e25f61ef939
Revises: f3bd7a3e8795
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0e25f61ef939"
down_revision: str | None = "f3bd7a3e8795"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("profile", sa.String(length=32), nullable=False),
        sa.Column("group_key", sa.String(length=160), nullable=False),
        sa.Column("capture_time", sa.String(length=40), nullable=True),
        sa.Column("camera_make", sa.String(length=64), nullable=True),
        sa.Column("camera_model", sa.String(length=128), nullable=True),
        sa.Column("camera_serial", sa.String(length=64), nullable=True),
        sa.Column("color_hint", sa.String(length=16), nullable=False),
        sa.Column("tb", sa.String(length=32), nullable=True),
        sa.Column("duration_ticks", sa.BigInteger(), nullable=True),
        sa.Column("rate", sa.String(length=32), nullable=True),
        sa.Column("vfr", sa.Boolean(), nullable=False),
        sa.Column("hfr", sa.Boolean(), nullable=False),
        sa.Column("display_width", sa.Integer(), nullable=True),
        sa.Column("display_height", sa.Integer(), nullable=True),
        sa.Column("rotation", sa.Integer(), nullable=False),
        sa.Column("video_stream_index", sa.Integer(), nullable=True),
        sa.Column("audio_stream_index", sa.Integer(), nullable=True),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_key"),
    )
    op.create_table(
        "media_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rel_path", sa.Text(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("mtime_ns", sa.BigInteger(), nullable=False),
        sa.Column("fingerprint", sa.String(length=80), nullable=False),
        sa.Column("media_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("probe_key", sa.String(length=128), nullable=True),
        sa.Column("container", sa.String(length=64), nullable=True),
        sa.Column("profile", sa.String(length=32), nullable=True),
        sa.Column("capture_time", sa.String(length=40), nullable=True),
        sa.Column("camera_make", sa.String(length=64), nullable=True),
        sa.Column("camera_model", sa.String(length=128), nullable=True),
        sa.Column("bit_rate", sa.BigInteger(), nullable=True),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rel_path"),
    )
    with op.batch_alter_table("media_file", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_media_file_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_media_file_fingerprint"), ["fingerprint"], unique=False
        )

    op.create_table(
        "asset_file",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("logical_start_ticks", sa.BigInteger(), nullable=False),
        sa.Column("duration_ticks", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_file.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "order"),
    )
    op.create_table(
        "media_stream",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("stream_index", sa.Integer(), nullable=False),
        sa.Column("codec_type", sa.String(length=16), nullable=False),
        sa.Column("codec_name", sa.String(length=32), nullable=True),
        sa.Column("codec_tag", sa.String(length=16), nullable=True),
        sa.Column("profile", sa.String(length=64), nullable=True),
        sa.Column("time_base", sa.String(length=32), nullable=False),
        sa.Column("start_pts", sa.BigInteger(), nullable=False),
        sa.Column("duration_ts", sa.BigInteger(), nullable=True),
        sa.Column("nb_frames", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("rate", sa.String(length=32), nullable=True),
        sa.Column("avg_rate", sa.String(length=32), nullable=True),
        sa.Column("vfr", sa.Boolean(), nullable=False),
        sa.Column("rotation", sa.Integer(), nullable=False),
        sa.Column("pix_fmt", sa.String(length=32), nullable=True),
        sa.Column("bit_depth", sa.Integer(), nullable=True),
        sa.Column("color_range", sa.String(length=8), nullable=True),
        sa.Column("color_transfer", sa.String(length=32), nullable=True),
        sa.Column("color_primaries", sa.String(length=32), nullable=True),
        sa.Column("color_space", sa.String(length=32), nullable=True),
        sa.Column("dovi", sa.Boolean(), nullable=False),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("channel_layout", sa.String(length=32), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("handler", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("media_stream", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_media_stream_media_file_id"), ["media_file_id"], unique=False
        )

    op.create_table(
        "sidecar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("owner_media_file_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("proxy_candidate", sa.Boolean(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_media_file_id"],
            ["media_file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sidecar", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sidecar_media_file_id"), ["media_file_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sidecar", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sidecar_media_file_id"))

    op.drop_table("sidecar")
    with op.batch_alter_table("media_stream", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_stream_media_file_id"))

    op.drop_table("media_stream")
    op.drop_table("asset_file")
    with op.batch_alter_table("media_file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_file_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_media_file_asset_id"))

    op.drop_table("media_file")
    op.drop_table("asset")
    # ### end Alembic commands ###
