"""embeddings, segments, similarity groups, sample dup reason

Revision ID: 698bfc268d9e
Revises: cfe7534ccb03
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "698bfc268d9e"
down_revision: str | None = "cfe7534ccb03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_kind", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("vector", sa.LargeBinary(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("embedding", schema=None) as batch_op:
        batch_op.create_index(
            "ix_embedding_owner", ["owner_kind", "owner_id", "model"], unique=False
        )

    op.create_table(
        "similarity_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("best_segment_id", sa.Integer(), nullable=True),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "segment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("shot_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("start_ticks", sa.BigInteger(), nullable=False),
        sa.Column("end_ticks", sa.BigInteger(), nullable=False),
        sa.Column("usable_start_ticks", sa.BigInteger(), nullable=False),
        sa.Column("usable_end_ticks", sa.BigInteger(), nullable=False),
        sa.Column("has_speech", sa.Boolean(), nullable=False),
        sa.Column("quality", sa.Float(), nullable=True),
        sa.Column("similarity_group_id", sa.Integer(), nullable=True),
        sa.Column("group_best", sa.Boolean(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["shot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["similarity_group_id"],
            ["similarity_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("segment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_segment_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_segment_shot_id"), ["shot_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_segment_similarity_group_id"), ["similarity_group_id"], unique=False
        )

    with op.batch_alter_table("sample_frame", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dup_reason", sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sample_frame", schema=None) as batch_op:
        batch_op.drop_column("dup_reason")

    with op.batch_alter_table("segment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segment_similarity_group_id"))
        batch_op.drop_index(batch_op.f("ix_segment_shot_id"))
        batch_op.drop_index(batch_op.f("ix_segment_asset_id"))

    op.drop_table("segment")
    op.drop_table("similarity_group")
    with op.batch_alter_table("embedding", schema=None) as batch_op:
        batch_op.drop_index("ix_embedding_owner")

    op.drop_table("embedding")
    # ### end Alembic commands ###
