"""L2: mosaics, tiles, visual observations, dispositions

Revision ID: 7e3c67768fd1
Revises: 698bfc268d9e
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7e3c67768fd1"
down_revision: str | None = "698bfc268d9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mosaic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("image_key", sa.String(length=128), nullable=False),
        sa.Column("cols", sa.Integer(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("tile_width", sa.Integer(), nullable=False),
        sa.Column("tile_height", sa.Integer(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mosaic", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mosaic_asset_id"), ["asset_id"], unique=False)

    op.create_table(
        "disposition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=True),
        sa.Column("anchor_start_ticks", sa.BigInteger(), nullable=False),
        sa.Column("anchor_end_ticks", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("disposition", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_disposition_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_disposition_segment_id"), ["segment_id"], unique=False)
        batch_op.create_index(
            "ux_disposition_segment_source", ["segment_id", "source"], unique=True
        )

    op.create_table(
        "mosaic_tile",
        sa.Column("mosaic_id", sa.Integer(), nullable=False),
        sa.Column("tile", sa.Integer(), nullable=False),
        sa.Column("sample_id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("ticks", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mosaic_id"],
            ["mosaic.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["sample_frame.id"],
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segment.id"],
        ),
        sa.PrimaryKeyConstraint("mosaic_id", "tile"),
    )
    with op.batch_alter_table("mosaic_tile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mosaic_tile_segment_id"), ["segment_id"], unique=False)

    op.create_table(
        "visual_observation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("mosaic_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mosaic_id"],
            ["mosaic.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("segment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visual_observation")
    with op.batch_alter_table("mosaic_tile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mosaic_tile_segment_id"))

    op.drop_table("mosaic_tile")
    with op.batch_alter_table("disposition", schema=None) as batch_op:
        batch_op.drop_index("ux_disposition_segment_source")
        batch_op.drop_index(batch_op.f("ix_disposition_segment_id"))
        batch_op.drop_index(batch_op.f("ix_disposition_asset_id"))

    op.drop_table("disposition")
    with op.batch_alter_table("mosaic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mosaic_asset_id"))

    op.drop_table("mosaic")
    # ### end Alembic commands ###
