"""editing: edit and edit_version

Revision ID: 9d6369774c0a
Revises: 7e3c67768fd1
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9d6369774c0a"
down_revision: str | None = "7e3c67768fd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid"),
    )
    op.create_table(
        "edit_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("edit_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_version", sa.Integer(), nullable=True),
        sa.Column("creator", sa.String(length=8), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("rate", sa.String(length=32), nullable=False),
        sa.Column("beats", sa.JSON(), nullable=False),
        sa.Column("timeline", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["edit_id"],
            ["edit.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("edit_version", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_edit_version_edit_id"), ["edit_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_edit_version_key"), ["key"], unique=False)
        batch_op.create_index("ux_edit_version", ["edit_id", "version"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("edit_version", schema=None) as batch_op:
        batch_op.drop_index("ux_edit_version")
        batch_op.drop_index(batch_op.f("ix_edit_version_key"))
        batch_op.drop_index(batch_op.f("ix_edit_version_edit_id"))

    op.drop_table("edit_version")
    op.drop_table("edit")
    # ### end Alembic commands ###
