"""audio: VAD events, transcript segments and words

Revision ID: cfe7534ccb03
Revises: e4a91124bbc5
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cfe7534ccb03"
down_revision: str | None = "e4a91124bbc5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("start_ticks", sa.BigInteger(), nullable=False),
        sa.Column("end_ticks", sa.BigInteger(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audio_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audio_event_asset_id"), ["asset_id"], unique=False)

    op.create_table(
        "transcript_segment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("start_ticks", sa.BigInteger(), nullable=False),
        sa.Column("end_ticks", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("avg_logprob", sa.Float(), nullable=True),
        sa.Column("no_speech_prob", sa.Float(), nullable=True),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transcript_segment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transcript_segment_asset_id"), ["asset_id"], unique=False
        )

    op.create_table(
        "transcript_word",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("start_ticks", sa.BigInteger(), nullable=False),
        sa.Column("end_ticks", sa.BigInteger(), nullable=False),
        sa.Column("word", sa.Text(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["transcript_segment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transcript_word", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transcript_word_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_transcript_word_segment_id"), ["segment_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcript_word", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_word_segment_id"))
        batch_op.drop_index(batch_op.f("ix_transcript_word_asset_id"))

    op.drop_table("transcript_word")
    with op.batch_alter_table("transcript_segment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_segment_asset_id"))

    op.drop_table("transcript_segment")
    with op.batch_alter_table("audio_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audio_event_asset_id"))

    op.drop_table("audio_event")
    # ### end Alembic commands ###
