"""render table

Revision ID: d341738442d4
Revises: 9d6369774c0a
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d341738442d4"
down_revision: str | None = "9d6369774c0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "render",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("edit_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("finished_at", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["edit_id"],
            ["edit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("render", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_render_edit_id"), ["edit_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("render", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_render_edit_id"))

    op.drop_table("render")
    # ### end Alembic commands ###
