"""L1: shots, sample frames, tech metrics

Revision ID: e4a91124bbc5
Revises: 0e25f61ef939
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e4a91124bbc5"
down_revision: str | None = "0e25f61ef939"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("start_ticks", sa.BigInteger(), nullable=False),
        sa.Column("end_ticks", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shot_asset_id"), ["asset_id"], unique=False)

    op.create_table(
        "sample_frame",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("shot_id", sa.Integer(), nullable=False),
        sa.Column("ticks", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=16), nullable=False),
        sa.Column("phash", sa.String(length=16), nullable=False),
        sa.Column("kept", sa.Boolean(), nullable=False),
        sa.Column("dup_of", sa.Integer(), nullable=True),
        sa.Column("image_key", sa.String(length=128), nullable=True),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dup_of"],
            ["sample_frame.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["shot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sample_frame", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sample_frame_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sample_frame_shot_id"), ["shot_id"], unique=False)

    op.create_table(
        "tech_metric",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("sample_id", sa.Integer(), nullable=True),
        sa.Column("start_ticks", sa.BigInteger(), nullable=False),
        sa.Column("end_ticks", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("percentile", sa.Float(), nullable=True),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["provenance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["sample_frame.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tech_metric", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tech_metric_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tech_metric_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_tech_metric_sample_id"), ["sample_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tech_metric", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tech_metric_sample_id"))
        batch_op.drop_index(batch_op.f("ix_tech_metric_name"))
        batch_op.drop_index(batch_op.f("ix_tech_metric_asset_id"))

    op.drop_table("tech_metric")
    with op.batch_alter_table("sample_frame", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sample_frame_shot_id"))
        batch_op.drop_index(batch_op.f("ix_sample_frame_asset_id"))

    op.drop_table("sample_frame")
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shot_asset_id"))

    op.drop_table("shot")
    # ### end Alembic commands ###
